In [12]:
import pandas as pd

df = pd.read_csv("/content/Crops_data.csv")
print(df)

      Dist Code  Year  State Code    State Name  Dist Name  \
0             1  2010          14  Chhattisgarh       Durg
1             1  2011          14  Chhattisgarh       Durg
2             1  2012          14  Chhattisgarh       Durg
3             1  2013          14  Chhattisgarh       Durg
4             1  2014          14  Chhattisgarh       Durg
...         ...   ...         ...           ...        ...
2479        917  2013          15     Jharkhand  Singhbhum
2480        917  2014          15     Jharkhand  Singhbhum
2481        917  2015          15     Jharkhand  Singhbhum
2482        917  2016          15     Jharkhand  Singhbhum
2483        917  2017          15     Jharkhand  Singhbhum

      RICE AREA (1000 ha)  RICE PRODUCTION (1000 tons)  \
0                  777.92                      1319.18
1                  806.55                      1416.48
2                  807.07                      1534.22
3                  819.44                      1296.24
4                  834.87                      1444.24
...                   ...                          ...
2479               267.06                       579.70
2480               256.33                       586.63
2481               263.21                       264.71
2482               224.05                       319.01
2483               386.91                       669.97

      RICE YIELD (Kg per ha)  WHEAT AREA (1000 ha)  \
0                    1695.77                 46.12
1                    1756.23                 44.98
2                    1900.97                 43.87
3                    1581.86                 41.54
4                    1729.89                 44.25
...                      ...                   ...
2479                 2170.67                  1.53
2480                 2288.57                  5.36
2481                 1005.70                  1.99
2482                 1423.84                  0.38
2483                 1731.62                  0.00

      WHEAT PRODUCTION (1000 tons)  ...  SUGARCANE YIELD (Kg per ha)  \
0                            45.87  ...                       256.96
1                            50.19  ...                       506.02
2                            47.69  ...                       252.98
3                            43.33  ...                       237.45
4                            50.96  ...                       602.17
...                            ...  ...                          ...
2479                          1.85  ...                         0.00
2480                          6.65  ...                         0.00
2481                          1.82  ...                         0.00
2482                          0.83  ...                         0.00
2483                          0.00  ...                         0.00

      COTTON AREA (1000 ha)  COTTON PRODUCTION (1000 tons)  \
0                      0.00                           0.00
1                      0.08                           0.02
2                      0.13                           0.02
3                      0.05                           0.01
4                      0.05                           0.02
...                     ...                            ...
2479                   0.00                           0.00
2480                   0.00                           0.00
2481                   0.00                           0.00
2482                   0.00                           0.00
2483                   0.00                           0.00

      COTTON YIELD (Kg per ha)  FRUITS AREA (1000 ha)  \
0                         0.00                   2.00
1                       250.00                   0.00
2                       153.85                   1.99
3                       200.00                   1.90
4                       400.00                   0.00
...                        ...                    ...
2479                      0.00                   0.00
2480                      0.00                   0.00
2481                      0.00                   0.00
2482                      0.00                   0.03
2483                      0.00                   0.00

      VEGETABLES AREA (1000 ha)  FRUITS AND VEGETABLES AREA (1000 ha)  \
0                         32.29                                 34.30
1                          0.00                                  0.00
2                         33.70                                 35.69
3                         32.83                                 34.74
4                          0.00                                  0.00
...                         ...                                   ...
2479                       9.02                                  9.03
2480                       8.63                                  8.64
2481                       6.84                                  6.85
2482                       6.40                                  6.43
2483                       0.00                                  0.00

      POTATOES AREA (1000 ha)  ONION AREA (1000 ha)  FODDER AREA (1000 ha)
0                        0.11                  0.49                   0.15
1                        0.12                  0.54                   0.00
2                        0.12                  0.54                   1.32
3                        0.11                  0.50                   0.77
4                        0.33                  0.51                   0.00
...                       ...                   ...                    ...
2479                     0.48                  0.08                   0.00
2480                     0.46                  0.04                   0.00
2481                     0.42                  0.01                   0.00
2482                     0.03                  0.01                   0.00
2483                     0.00                  0.00                   0.00

[2484 rows x 80 columns]

In [ ]:
df.describe()

,Dist Code,Year,State Code,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),WHEAT AREA (1000 ha),WHEAT PRODUCTION (1000 tons),WHEAT YIELD (Kg per ha),KHARIF SORGHUM AREA (1000 ha),...,SUGARCANE YIELD (Kg per ha),COTTON AREA (1000 ha),COTTON PRODUCTION (1000 tons),COTTON YIELD (Kg per ha),FRUITS AREA (1000 ha),VEGETABLES AREA (1000 ha),FRUITS AND VEGETABLES AREA (1000 ha),POTATOES AREA (1000 ha),ONION AREA (1000 ha),FODDER AREA (1000 ha)
count,2484.000000,2484.000000,2484.000000,2484.000000,2484.000000,2484.000000,2484.000000,2484.000000,2484.000000,2484.000000,...,2484.000000,2484.000000,2484.000000,2484.000000,2484.000000,2484.000000,2484.000000,2484.000000,2484.000000,2484.000000
mean,270.787440,2013.497987,9.579710,136.178760,343.644275,2080.995036,97.725334,320.235576,2122.398023,7.664654,...,4990.710370,38.805564,15.990358,183.548305,9.660862,14.777689,23.635874,4.739316,1.758941,20.382190
std,279.103876,2.292275,4.993319,165.873301,450.543743,1122.429915,122.065775,511.080609,1358.602497,19.644234,...,3545.974487,97.019304,43.040833,297.351559,17.558463,24.605025,34.156832,12.381880,6.127979,90.339773
min,1.000000,2010.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,78.000000,2011.000000,6.000000,8.900000,15.322500,1355.445000,0.965000,1.465000,1200.000000,0.000000,...,1055.792500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,156.000000,2013.000000,10.000000,79.675000,178.145000,2178.335000,48.970000,90.635000,2075.610000,0.190000,...,5734.975000,0.000000,0.000000,0.000000,0.935000,5.565000,9.530000,0.420000,0.230000,0.150000
75%,242.000000,2015.250000,12.000000,207.575000,496.267500,2747.137500,162.557500,496.132500,3127.477500,4.202500,...,7338.447500,14.647500,4.707500,335.860000,10.935000,17.460000,31.422500,4.185000,1.050000,7.542500
max,917.000000,2017.000000,20.000000,1154.230000,3215.010000,5653.830000,879.490000,4305.500000,5541.520000,175.000000,...,22062.300000,800.890000,376.610000,2857.740000,117.080000,191.830000,240.990000,111.610000,131.350000,1162.660000

In [13]:
df.isnull().sum()

Dist Code                               0
Year                                    0
State Code                              0
State Name                              0
Dist Name                               0
                                       ..
VEGETABLES AREA (1000 ha)               0
FRUITS AND VEGETABLES AREA (1000 ha)    0
POTATOES AREA (1000 ha)                 0
ONION AREA (1000 ha)                    0
FODDER AREA (1000 ha)                   0
Length: 80, dtype: int64

In [14]:
df.dropna()

,Dist Code,Year,State Code,State Name,Dist Name,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),WHEAT AREA (1000 ha),WHEAT PRODUCTION (1000 tons),...,SUGARCANE YIELD (Kg per ha),COTTON AREA (1000 ha),COTTON PRODUCTION (1000 tons),COTTON YIELD (Kg per ha),FRUITS AREA (1000 ha),VEGETABLES AREA (1000 ha),FRUITS AND VEGETABLES AREA (1000 ha),POTATOES AREA (1000 ha),ONION AREA (1000 ha),FODDER AREA (1000 ha)
0,1,2010,14,Chhattisgarh,Durg,777.92,1319.18,1695.77,46.12,45.87,...,256.96,0.00,0.00,0.00,2.00,32.29,34.30,0.11,0.49,0.15
1,1,2011,14,Chhattisgarh,Durg,806.55,1416.48,1756.23,44.98,50.19,...,506.02,0.08,0.02,250.00,0.00,0.00,0.00,0.12,0.54,0.00
2,1,2012,14,Chhattisgarh,Durg,807.07,1534.22,1900.97,43.87,47.69,...,252.98,0.13,0.02,153.85,1.99,33.70,35.69,0.12,0.54,1.32
3,1,2013,14,Chhattisgarh,Durg,819.44,1296.24,1581.86,41.54,43.33,...,237.45,0.05,0.01,200.00,1.90,32.83,34.74,0.11,0.50,0.77
4,1,2014,14,Chhattisgarh,Durg,834.87,1444.24,1729.89,44.25,50.96,...,602.17,0.05,0.02,400.00,0.00,0.00,0.00,0.33,0.51,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2479,917,2013,15,Jharkhand,Singhbhum,267.06,579.70,2170.67,1.53,1.85,...,0.00,0.00,0.00,0.00,0.00,9.02,9.03,0.48,0.08,0.00
2480,917,2014,15,Jharkhand,Singhbhum,256.33,586.63,2288.57,5.36,6.65,...,0.00,0.00,0.00,0.00,0.00,8.63,8.64,0.46,0.04,0.00
2481,917,2015,15,Jharkhand,Singhbhum,263.21,264.71,1005.70,1.99,1.82,...,0.00,0.00,0.00,0.00,0.00,6.84,6.85,0.42,0.01,0.00
2482,917,2016,15,Jharkhand,Singhbhum,224.05,319.01,1423.84,0.38,0.83,...,0.00,0.00,0.00,0.00,0.03,6.40,6.43,0.03,0.01,0.00
2483,917,2017,15,Jharkhand,Singhbhum,386.91,669.97,1731.62,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [ ]:
df.columns

Index(['Dist Code', 'Year', 'State Code', 'State Name', 'Dist Name',
       'RICE AREA (1000 ha)', 'RICE PRODUCTION (1000 tons)',
       'RICE YIELD (Kg per ha)', 'WHEAT AREA (1000 ha)',
       'WHEAT PRODUCTION (1000 tons)', 'WHEAT YIELD (Kg per ha)',
       'KHARIF SORGHUM AREA (1000 ha)',
       'KHARIF SORGHUM PRODUCTION (1000 tons)',
       'KHARIF SORGHUM YIELD (Kg per ha)', 'RABI SORGHUM AREA (1000 ha)',
       'RABI SORGHUM PRODUCTION (1000 tons)', 'RABI SORGHUM YIELD (Kg per ha)',
       'SORGHUM AREA (1000 ha)', 'SORGHUM PRODUCTION (1000 tons)',
       'SORGHUM YIELD (Kg per ha)', 'PEARL MILLET AREA (1000 ha)',
       'PEARL MILLET PRODUCTION (1000 tons)', 'PEARL MILLET YIELD (Kg per ha)',
       'MAIZE AREA (1000 ha)', 'MAIZE PRODUCTION (1000 tons)',
       'MAIZE YIELD (Kg per ha)', 'FINGER MILLET AREA (1000 ha)',
       'FINGER MILLET PRODUCTION (1000 tons)',
       'FINGER MILLET YIELD (Kg per ha)', 'BARLEY AREA (1000 ha)',
       'BARLEY PRODUCTION (1000 tons)', 'BARLEY YIELD (Kg per ha)',
       'CHICKPEA AREA (1000 ha)', 'CHICKPEA PRODUCTION (1000 tons)',
       'CHICKPEA YIELD (Kg per ha)', 'PIGEONPEA AREA (1000 ha)',
       'PIGEONPEA PRODUCTION (1000 tons)', 'PIGEONPEA YIELD (Kg per ha)',
       'MINOR PULSES AREA (1000 ha)', 'MINOR PULSES PRODUCTION (1000 tons)',
       'MINOR PULSES YIELD (Kg per ha)', 'GROUNDNUT AREA (1000 ha)',
       'GROUNDNUT PRODUCTION (1000 tons)', 'GROUNDNUT YIELD (Kg per ha)',
       'SESAMUM AREA (1000 ha)', 'SESAMUM PRODUCTION (1000 tons)',
       'SESAMUM YIELD (Kg per ha)', 'RAPESEED AND MUSTARD AREA (1000 ha)',
       'RAPESEED AND MUSTARD PRODUCTION (1000 tons)',
       'RAPESEED AND MUSTARD YIELD (Kg per ha)', 'SAFFLOWER AREA (1000 ha)',
       'SAFFLOWER PRODUCTION (1000 tons)', 'SAFFLOWER YIELD (Kg per ha)',
       'CASTOR AREA (1000 ha)', 'CASTOR PRODUCTION (1000 tons)',
       'CASTOR YIELD (Kg per ha)', 'LINSEED AREA (1000 ha)',
       'LINSEED PRODUCTION (1000 tons)', 'LINSEED YIELD (Kg per ha)',
       'SUNFLOWER AREA (1000 ha)', 'SUNFLOWER PRODUCTION (1000 tons)',
       'SUNFLOWER YIELD (Kg per ha)', 'SOYABEAN AREA (1000 ha)',
       'SOYABEAN PRODUCTION (1000 tons)', 'SOYABEAN YIELD (Kg per ha)',
       'OILSEEDS AREA (1000 ha)', 'OILSEEDS PRODUCTION (1000 tons)',
       'OILSEEDS YIELD (Kg per ha)', 'SUGARCANE AREA (1000 ha)',
       'SUGARCANE PRODUCTION (1000 tons)', 'SUGARCANE YIELD (Kg per ha)',
       'COTTON AREA (1000 ha)', 'COTTON PRODUCTION (1000 tons)',
       'COTTON YIELD (Kg per ha)', 'FRUITS AREA (1000 ha)',
       'VEGETABLES AREA (1000 ha)', 'FRUITS AND VEGETABLES AREA (1000 ha)',
       'POTATOES AREA (1000 ha)', 'ONION AREA (1000 ha)',
       'FODDER AREA (1000 ha)'],
      dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
X = df[["RICE AREA (1000 ha)", "RICE PRODUCTION (1000 tons)", "Year"]]
y = df["RICE YIELD (Kg per ha)"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

In [ ]:
score=model.score(X_test,y_test)
print(score)

In [ ]:
y_pred=model.predict(X_test)

In [ ]:
print(y_pred)

In [ ]:
# import warnings
# warnings.filterwarnings("ignore")
# rice1 = float(input("Enter Your Rice Area: "))
# rice2 = float(input("Enter Your Rice Production: "))
# rice3 = int(input("Enter Your Year: "))

# sample = [[rice1, rice2, rice3]]
# y_pred = model.predict(sample)

# print("Predicted Rice Yield (Kg/ha):", y_pred[0])

In [ ]:
import pickle
with open('model.pkl','wb') as file:
  pickle.dump(model,file)